method: auto   # 'auto' → varsa models/isotonic_v1.joblib kullan; yoksa percentile_map
knots:
  - [0,   10]
  - [10,  25]
  - [25,  40]
  - [50,  55]
  - [75,  70]
  - [90,  85]
  - [100, 100]
in_path:  "data/processed/scores_v01.parquet"
out_path: "data/processed/scores_v02_calibrated.parquet"
